package com.example.koracards.network

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import java.net.Inet4Address
import java.net.NetworkInterface
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Singleton orchestrator for all peer-to-peer networking.
 *
 * **Host flow:**
 * 1. Call [startAsHost] → room code displayed; UDP broadcasting begins.
 * 2. Guest connects → [connectionState] becomes [ConnectionState.Connected].
 * 3. Call [stopBroadcasting] once the guest is confirmed (after receiving [GameMessage.NicknameSync]).
 * 4. Exchange [GameMessage]s via [send] / [incomingMessages].
 * 5. Call [disconnect] on game end or navigation away.
 *
 * **Guest flow:**
 * 1. Call [startAsGuest] with the room code → UDP listener starts.
 * 2. Host found → WebSocket connection initiated automatically.
 * 3. [connectionState] becomes [ConnectionState.Connected] on handshake success.
 * 4. Exchange messages; [disconnect] on game end.
 *
 * All public methods are safe to call from any thread.
 */
@Singleton
class NetworkManager @Inject constructor(
    @param:ApplicationContext private val context: Context
) {
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    // -----------------------------------------------------------------------
    // Public streams
    // -----------------------------------------------------------------------

    private val _incomingMessages = MutableSharedFlow<GameMessage>(extraBufferCapacity = 128)
    /** Unified incoming message stream — collects from server or client depending on role. */
    val incomingMessages: SharedFlow<GameMessage> = _incomingMessages

    private val _connectionState = MutableStateFlow<ConnectionState>(ConnectionState.Lost)
    /** Live connection state. Observe this in ViewModels to react to drops/reconnects. */
    val connectionState: StateFlow<ConnectionState> = _connectionState

    // -----------------------------------------------------------------------
    // Internal components (nullable until the role is chosen)
    // -----------------------------------------------------------------------

    private var isHost = false
    private var server: GameWebSocketServer? = null
    private var client: GameWebSocketClient? = null
    private var broadcaster: UdpBroadcaster? = null
    private var listener: UdpListener? = null

    /** Bridge jobs — cancelled on [disconnect]. */
    private val bridgeJobs = mutableListOf<Job>()

    // -----------------------------------------------------------------------
    // Role setup
    // -----------------------------------------------------------------------

    /**
     * Configures this device as the **host**.
     * Starts the WebSocket server and UDP broadcaster immediately.
     *
     * @param roomCode The 4-char code to broadcast (generated by [RoomCodeGenerator]).
     */
    fun startAsHost(roomCode: String) {
        isHost = true
        tearDownComponents()

        val srv = GameWebSocketServer()
        server = srv
        srv.start()

        val (ip, broadcastIp) = getHotspotAddress()
        val bcast = UdpBroadcaster(roomCode, ip, broadcastIp, srv.port)
        broadcaster = bcast
        bcast.start(scope)

        bridgeJobs += scope.launch {
            srv.connectionState.collect { _connectionState.value = it }
        }
        bridgeJobs += scope.launch {
            srv.incomingMessages.collect { _incomingMessages.emit(it) }
        }
    }

    /**
     * Configures this device as the **guest**.
     * Starts the UDP listener; the WebSocket client is created automatically once the host is found.
     *
     * @param roomCode The 4-char code entered by the user on the Join Game screen.
     */
    fun startAsGuest(roomCode: String) {
        isHost = false
        tearDownComponents()

        val lst = UdpListener()
        listener = lst
        lst.start(scope, roomCode) { ip, port ->
            lst.stop()
            listener = null

            val cli = GameWebSocketClient(ip, port)
            client = cli
            cli.connect(scope)

            bridgeJobs += scope.launch {
                cli.connectionState.collect { _connectionState.value = it }
            }
            bridgeJobs += scope.launch {
                cli.incomingMessages.collect { _incomingMessages.emit(it) }
            }
        }
    }

    // -----------------------------------------------------------------------
    // Messaging
    // -----------------------------------------------------------------------

    /**
     * Sends [message] to the peer device.
     * Must be called from a coroutine. No-ops if not connected.
     */
    suspend fun send(message: GameMessage) {
        if (isHost) {
            server?.send(message)
        } else {
            client?.send(message)
        }
    }

    // -----------------------------------------------------------------------
    // Lifecycle helpers
    // -----------------------------------------------------------------------

    /**
     * Stops UDP broadcasting (host only).
     * Call this once the guest has connected to avoid polluting the LAN with stale packets.
     * Typically invoked after receiving [GameMessage.NicknameSync].
     */
    fun stopBroadcasting() {
        broadcaster?.stop()
        broadcaster = null
    }

    /** Tears down all components and cancels bridge jobs. */
    fun disconnect() {
        tearDownComponents()
        _connectionState.value = ConnectionState.Lost
    }

    // -----------------------------------------------------------------------
    // Internals
    // -----------------------------------------------------------------------

    private fun tearDownComponents() {
        bridgeJobs.forEach { it.cancel() }
        bridgeJobs.clear()
        broadcaster?.stop()
        listener?.stop()
        server?.stop()
        client?.disconnect()
        broadcaster = null
        listener = null
        server = null
        client = null
    }

    private fun getHotspotAddress(): Pair<String, String> {
        val preferredPrefixes = listOf("ap", "wlan", "swlan", "rmnet")
        val interfaces = runCatching { NetworkInterface.getNetworkInterfaces()?.toList() }.getOrNull() ?: emptyList()

        // Try preferred hotspot/wifi interfaces first
        for (prefix in preferredPrefixes) {
            for (iface in interfaces) {
                if (!iface.name.startsWith(prefix) || !iface.isUp) continue
                for (addr in iface.interfaceAddresses) {
                    val inet = addr.address
                    if (inet !is Inet4Address || inet.isLoopbackAddress) continue
                    val ip = inet.hostAddress ?: continue
                    val broadcast = addr.broadcast?.hostAddress ?: computeBroadcast(inet, addr.networkPrefixLength)
                    return Pair(ip, broadcast)
                }
            }
        }

        // Fallback: any non-loopback IPv4
        for (iface in interfaces) {
            for (addr in iface.interfaceAddresses) {
                val inet = addr.address
                if (inet !is Inet4Address || inet.isLoopbackAddress) continue
                val ip = inet.hostAddress ?: continue
                val broadcast = addr.broadcast?.hostAddress ?: "255.255.255.255"
                return Pair(ip, broadcast)
            }
        }
        return Pair("0.0.0.0", "255.255.255.255")
    }

    private fun computeBroadcast(ip: Inet4Address, prefixLen: Short): String {
        val ipInt = ip.address.fold(0) { acc, b -> (acc shl 8) or (b.toInt() and 0xFF) }
        val mask = if (prefixLen <= 0) 0 else (-1 shl (32 - prefixLen))
        val broadcastInt = (ipInt and mask) or mask.inv()
        return (24 downTo 0 step 8).joinToString(".") { shift -> ((broadcastInt shr shift) and 0xFF).toString() }
    }
}
