package com.example.koracards.network

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress

/** UDP port used for room-code discovery broadcasts. */
internal const val UDP_PORT = 47_777

/**
 * Host-side UDP broadcaster.
 *
 * Sends a JSON payload `{"roomCode":"XXXX","ip":"192.168.x.x","port":NNNNN}` to the LAN
 * broadcast address (`255.255.255.255`) on [UDP_PORT] every 1 second.
 *
 * Call [start] once the WebSocket server is ready. Call [stop] as soon as the guest connects
 * (typically after receiving [GameMessage.NicknameSync]).
 *
 * @param roomCode The 4-char code generated by [RoomCodeGenerator].
 * @param hostIp   The host device's LAN IPv4 address (obtained from [NetworkManager]).
 * @param serverPort The WebSocket server port (OS-assigned — obtained from [GameWebSocketServer.port]).
 */
class UdpBroadcaster(
    private val roomCode: String,
    private val hostIp: String,
    private val broadcastIp: String,
    private val serverPort: Int
) {
    private var job: Job? = null

    /** Starts broadcasting on [scope]'s [Dispatchers.IO]. Safe to call multiple times — restarts if already stopped. */
    fun start(scope: CoroutineScope) {
        stop() // cancel any existing job first
        job = scope.launch(Dispatchers.IO) {
            val socket = DatagramSocket()
            socket.broadcast = true
            val broadcastAddress = InetAddress.getByName(broadcastIp)
            val fallbackAddress = InetAddress.getByName("255.255.255.255")
            // Build the JSON payload inline — avoid kotlinx.serialization overhead for this simple struct
            val payload = """{"roomCode":"$roomCode","ip":"$hostIp","port":$serverPort}"""
            val bytes = payload.toByteArray(Charsets.UTF_8)
            try {
                while (isActive) {
                    val packet = DatagramPacket(bytes, bytes.size, broadcastAddress, UDP_PORT)
                    runCatching { socket.send(packet) } // ignore transient send errors
                    
                    if (broadcastIp != "255.255.255.255") {
                        val fallbackPacket = DatagramPacket(bytes, bytes.size, fallbackAddress, UDP_PORT)
                        runCatching { socket.send(fallbackPacket) }
                    }
                    delay(1_000L)
                }
            } finally {
                runCatching { socket.close() }
            }
        }
    }

    /** Stops the broadcast loop and closes the socket. */
    fun stop() {
        job?.cancel()
        job = null
    }
}
